document.addEventListener("DOMContentLoaded", function() {
    const quotes = [
        { text: "Life is like riding a bicycle. To keep your balance you must keep moving.", author: "Albert Einstein" },
        { text: "The important thing is not to stop questioning. Curiosity has its own reason for existing.", author: "Albert Einstein" },
        { text: "Study hard what interests you the most in the most undisciplined, irreverent and original manner possible.", author: "Richard Feynman" },
        { text: "The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.", author: "Stephen Hawking" },
        { text: "Science is a way of thinking much more than it is a body of knowledge.", author: "Carl Sagan" },
        { text: "If something is important enough, even if the odds are against you, you should still do it.", author: "Elon Musk" },
        { text: "When something is important enough, you do it even if the odds are not in your favor.", author: "Elon Musk" },
        { text: "The first step is to establish that something is possible; then probability will occur.", author: "Elon Musk" },
        { text: "A company is only as good as its people and how excited they are about creating.", author: "Elon Musk" },
        { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
        { text: "Knowledge speaks, but wisdom listens.", author: "Jimi Hendrix" },
        { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
        { text: "I have no special talents. I am only passionately curious.", author: "Albert Einstein" },
        { text: "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.", author: "Albert Einstein" },
        { text: "Reality is just a crutch for people who can’t cope with drugs.", author: "Robin Williams" },
        { text: "The best way to predict the future is to invent it.", author: "Alan Kay" },
        { text: "Any sufficiently advanced technology is indistinguishable from magic.", author: "Arthur C. Clarke" },
        { text: "You don’t learn to walk by following rules. You learn by doing, and by falling over.", author: "Richard Branson" },
        { text: "Your brand is what other people say about you when you’re not in the room.", author: "Jeff Bezos" },
        { text: "If you double the number of experiments you do per year, you’re going to double your inventiveness.", author: "Jeff Bezos" },
        { text: "Work like hell. I mean you just have to put in 80 to 100-hour weeks every week.", author: "Elon Musk" },
        { text: "Compound interest is the eighth wonder of the world. He who understands it, earns it ... he who doesn’t ... pays it.", author: "Albert Einstein" },
        { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
        { text: "Make something people want.", author: "Paul Graham" },
        { text: "It’s hard to do a really good job on anything you don’t think about in the shower.", author: "Paul Graham" },
        { text: "Do things that don’t scale.", author: "Paul Graham" },
        { text: "Find something more important than you are and dedicate your life to it.", author: "Daniel Dennett" },
        { text: "Don’t let schooling interfere with your education.", author: "Mark Twain" },
        { text: "A year from now you may wish you had started today.", author: "Karen Lamb" },
        { text: "If you don’t build your dream, someone else will hire you to help them build theirs.", author: "Tony Gaskins" },
        { text: "Happiness is a choice and a skill and you can dedicate yourself to learning that skill and making that choice.", author: "Naval Ravikant" },
        { text: "Play long-term games with long-term people.", author: "Naval Ravikant" },
        { text: "You should be too busy to 'do coffee,' while still keeping an uncluttered calendar.", author: "Naval Ravikant" },
        { text: "If you want to be wealthy, spend less time chasing money and more time learning how money works.", author: "Naval Ravikant" },
        { text: "Escape competition through authenticity.", author: "Naval Ravikant" },
        { text: "Earn with your mind, not your time.", author: "Naval Ravikant" },
        { text: "A calm mind, a fit body, and a house full of love. These things cannot be bought. They must be earned.", author: "Naval Ravikant" },
        { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
        { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
        { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
        { text: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
        { text: "Timing, perseverance, and ten years of trying will eventually make you look like an overnight success.", author: "Biz Stone" },
        { text: "If you don’t make things happen then things will happen to you.", author: "Robert Collier" },
        { text: "Success is getting what you want. Happiness is wanting what you get.", author: "Dale Carnegie" },
        { text: "We are what we repeatedly do. Excellence, then, is not an act but a habit.", author: "Will Durant" },
        { text: "It’s fine to celebrate success, but it is more important to heed the lessons of failure.", author: "Bill Gates" },
        { text: "Don’t compare yourself with anyone in this world… if you do so, you are insulting yourself.", author: "Bill Gates" },
        { text: "Invention is by its very nature disruptive. If you want to be understood at all times, then don’t do anything new.", author: "Jeff Bezos" },
        { text: "If you want to find the secrets of the universe, think in terms of energy, frequency, and vibration.", author: "Nikola Tesla" },
        { text: "The greatest wealth is to live content with little.", author: "Plato" },
        { text: "He who opens a school door, closes a prison.", author: "Victor Hugo" },
        { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
        { text: "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.", author: "Charles Darwin" },
        { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
        { text: "Your most unhappy customers are your greatest source of learning.", author: "Bill Gates" }
    ];
    

    const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
    const quoteElement = document.getElementById("quote");
    quoteElement.innerHTML = `"${randomQuote.text}" - ${randomQuote.author}`;
});